# Generated by Django 3.1.2 on 2020-10-22 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('detalhes', models.TextField()),
                ('preco', models.TextField()),
                ('garantia', models.IntegerField()),
                ('date_produto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
