# Generated by Django 3.1.2 on 2020-10-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuiTechnology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='garantia',
        ),
    ]
