# Generated by Django 3.1.2 on 2020-10-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('GuiTechnology', '0003_auto_20201022_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
            preserve_default=False,
        ),
    ]
