# Generated by Django 3.1.2 on 2020-10-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuiTechnology', '0004_produto_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
